### ISSUE TITLE
The dropbox link has expired

### ISSUE THREAD

**Issue by dyollb** [pydsgz/IEMap#1]
The Dropbox link no longer works and cloning the repository still yields an error:
> This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.

Could you please update the dropbox link, or add it here to this issue? Thanks

**Comment by mangotee** [comment]
That is correct, apologies for that. The link is now updated with a Google Drive link.

**Comment by dyollb** [comment]
Thanks!
